cleanup task

diff --git a/components/tekton/tasks/base/tox-task.yaml b/components/tekton/tasks/base/tox-task.yaml
--- a/components/tekton/tasks/base/tox-task.yaml
+++ b/components/tekton/tasks/base/tox-task.yaml
@@ -20,13 +20,13 @@ spec:
       description: The used Python version, more precisely the tag for the Python image
       type: string
       default: "latest"
+    - name: SOURCE_PATH
+      description: The path to the source code
+      default: "."
     - name: ARGS
       description: The additional arguments to be used with tox
       type: string
       default: "--parallel auto"
-    - name: SOURCE_PATH
-      description: The path to the source code
-      default: "."
     - name: REQUIREMENTS_FILE
       description: The name of the requirements file inside the source location, with fallback to the requirements file in the root location
       default: "requirements.txt"
@@ -39,23 +39,13 @@ spec:
       workingDir: $(workspaces.source.path)
       script: |
         export PATH=$PATH:$HOME/.local/bin
-
-        if [ -e "$(inputs.params.SOURCE_PATH)"/"$(inputs.params.REQUIREMENTS_FILE)" ];
-        then
-          pip install -r "$(inputs.params.SOURCE_PATH)"/"$(inputs.params.REQUIREMENTS_FILE)"
-          pip show tox || {
-            printf "###\nWarning: Tox is missing in your test requirements file\n###";
-            pip install tox
-          }
+        if [ -n "$(inputs.params.REQUIREMENTS_FILE)" ] && [ -e "$(inputs.params.REQUIREMENTS_FILE)" ];then
+           pip install -r $(inputs.params.SOURCE_PATH)/$(inputs.params.REQUIREMENTS_FILE)
+           pip show tox || {
+              echo "###\nWarning: Tox is missing in your requirements\n###";
+              pip install tox
+           }
         else
-          if [ -e "$(inputs.params.REQUIREMENTS_FILE)" ];
-          then
-            pip install -r "$(inputs.params.REQUIREMENTS_FILE)"
-          fi
-          pip install tox
+           pip install tox
         fi
-        if [ -z "$(inputs.params.ARGS)" ]; then
-          tox "$(inputs.params.SOURCE_PATH)"
-        else
-          tox $(inputs.params.ARGS) "$(inputs.params.SOURCE_PATH)"
-        fi
+        tox $(inputs.params.ARGS) $(inputs.params.SOURCE_PATH)
