add linting for all charts

diff --git a/.github/workflows/manifests-validation.yaml b/.github/workflows/manifests-validation.yaml
--- a/.github/workflows/manifests-validation.yaml
+++ b/.github/workflows/manifests-validation.yaml
@@ -41,6 +41,7 @@ jobs:
     runs-on: ubuntu-latest
     env:
       HELM_VERSION: 3.9.4
+      HELM_DIRS: .
     steps:
       - name: Install Helm
         run: |
@@ -49,4 +50,24 @@ jobs:
       - name: Code Checkout
         uses: actions/checkout@v2
       - name: Validate Manifests
-        run: helm lint components/charts/odh/
+        run: | 
+          for i in `find "${HELM_DIRS}" -name "Chart.yaml" -exec dirname {} \;`; 
+          do
+
+            echo
+            echo "Validating $i"
+            echo
+
+            ${HELM} lint $i
+
+            build_response=$?
+
+            if [ $build_response -ne 0 ]; then
+              echo "Error linting $i"
+              exit 1
+            fi
+            
+          done
+
+          echo
+          echo "Charts successfully validated!"
